### ISSUE TITLE
Failed to parse parameters: Failed to load unknown flag 'external_logger_cmd'

### ISSUE THREAD

**Issue by AbacusIntegrationPlatform** [wjoel/mesos-external-container-logger#3]
I am trying to use this in my Mesos Marathon installation. Its a custom installation, installed without root privilege in a custom directory. 
Mesos master and slave nodes are running without any issues. I then installed the External Logger module and try to start my slave. I am getting the below error -

E0101 21:09:41.246604 30807 lib_externallogger.cpp:269] Failed to parse parameters: Failed to load unknown flag 'external_logger_cmd'
E0101 21:09:41.248632 30807 main.cpp:489] EXIT with status 1: Failed to create a containerizer: Could not create DockerContainerizer: Failed to create container logger: Failed to create container logger module 'org_apache_mesos_ExternalContainerLogger': Error creating Module instance for 'org_apache_mesos_ExternalContainerLogger'

Command -

./mesos-agent.sh --master=127.0.0.1:5050 --work_dir=/u01/mesos/mesos-1.4.1/mesos_slave --no-systemd_enable_support --containerizers=docker,mesos --container_logger=org_apache_mesos_ExternalContainerLogger --modules=/u01/mesos/mesos-1.4.1/mesos_logs/mesos_external_logger.json

Content of mesos_external_logger.json -
{
  "libraries": [{
    "file": "/u01/mesos/libexternal_container_logger-0.1.4.so",
    "modules": [{
      "name": "org_apache_mesos_ExternalContainerLogger",
      "parameters": [{"value": "/u01/mesos/mesos-1.4.1/mesos_logs/filebeat-container-logger.sh",
                      "key": "external_logger_cmd"}]
    }]
  }]
}

**Comment by marc-lebourdais** [comment]
The documentation is wrong in the example you used. The correct key is `external_logger_binary` rather than `external_logger_cmd`.

**Comment by marc-lebourdais** [comment]
Check out the flags defined in the hpp file:
https://github.com/wjoel/mesos-external-container-logger/blob/master/src/lib_externallogger.hpp

**Comment by AbacusIntegrationPlatform** [comment]
Thanks. This particular issue is resolved. However, I am facing some other issue on generation of log files itself. If you can see the below image, the logs are empty. I tried to use the basic logging like the one below -
#!/bin/sh
cat > $(echo "$MESOS_LOG_STREAM" | tr '[:upper:]' '[:lower:]')

Then I tried using -
#!/bin/bash

log_level="info"
if [ "$MESOS_LOG_STREAM" = "STDERR" ]; then
  log_level="err"
fi

task_id=$(echo "$MESOS_EXECUTORINFO_JSON" | \
  /u01/mesos/jq-1.5/configure_dir/bin/jq -r '.command.environment.variables[]|select(.name=="MESOS_TASK_ID").value')

if [ "$task_id" ]; then
    task_identifier="-t $task_id"
fi

systemd-cat $task_identifier -p $log_level

![image](https://user-images.githubusercontent.com/29430500/34488073-0c58a9a2-effd-11e7-90c3-2329b5099fef.png)

Note that the log directory is also empty. No logs are being generated. This is how I am starting my agent
./bin/mesos-slave.sh --ip=x.x.x.x --master=zk://x.x.x.x:2181,y.y.y.y:2181/mesos --work_dir=/u01/mesos/mesos-1.4.1/mesos-slave --no-systemd_enable_support --containerizers=docker,mesos --executor_registration_timeout=5mins --log_dir=/u01/mesos/mesos-1.4.1/mesos-slave --container_logger=org_apache_mesos_ExternalContainerLogger --modules=/u01/mesos/mesos-1.4.1/mesos_logs/mesos_external_logger.json

**Comment by AbacusIntegrationPlatform** [comment]
Update -
My Mesos version is 1.4.1

**Comment by marc-lebourdais** [comment]
The first example is just going to redirect the container logs to stdout and stderr of the mesos agent's forked process that runs the external container logger, so you'd have to have that in the foreground to see the logs.

The second example writes to systemd, so you'll have to use journalctl to see those logs. This example is probably easier to see.

In neither case will you see a usual "log file" in the literal sense. Note that the script that gets run by the external container logger module will always read via stdin, so you could make the script just loop over stdin and write to some random file somewhere.

**Comment by marc-lebourdais** [comment]
In my use case for this, I wrote a small binary in Go that reads from stdin, does some log sanitization, injects some data from the environment variables, and then writes the modified log message to syslog (on Ubuntu 14.04).

**Comment by marc-lebourdais** [comment]
The first example is just going to redirect the container logs to stdout and stderr of the mesos agent's forked process that runs the external container logger, so you'd have to have that in the foreground to see the logs.

The second example writes to systemd, so you'll have to use journalctl to see those logs. This example is probably easier to see.

In neither case will you see a usual "log file" in the literal sense. Note that the script that gets run by the external container logger module will always read via stdin, so you could make the script just loop over stdin and write to some random file somewhere.

**Comment by AbacusIntegrationPlatform** [comment]
Thanks Marc. I could able to view the logs in Graylog now. My configuration is as below. I have an issue where mesos_fields are coming null. 

mesos_fields=$(echo "$MESOS_EXECUTORINFO_JSON" | \
                /u01/mesos/jq-1.5/bin/jq -r ".command.environment.variables
                         |map(\"\(.name):\(.value|tostring)\")|.[]" | \            
                awk -F: 'length($2) > 0 {
                           $1=tolower($1);
                           if (!match($1, "^mesos_.*")) {
                             $1="mesos_" $1;
                           }
                           printf("%s: \"%s\"\n        ", $1, $2);
                         }')

This is how i am launching the mesos agent.

./bin/mesos-slave.sh --ip=x.x.x.x --master=zk://x.x.x.x:2181/mesos --no-systemd_enable_support --work_dir=/u01/mesos/mesos-1.4.1/mesos_slave --containerizers=docker,mesos --executor_registration_timeout=30mins --log_dir=/u01/mesos/mesos-1.4.1/mesos_slave --container_logger=org_apache_mesos_ExternalContainerLogger  --modules=/u01/mesos/mesos-1.4.1/mesos_logs/mesos_external_logger.json

I am able to view everything in Graylog except mesos_fields values - like marathon_app_id etc.,

![image](https://user-images.githubusercontent.com/29430500/34531459-5b2abc6a-f0d8-11e7-9ebe-8a96b12e431f.png)

**Comment by marc-lebourdais** [comment]
Is `"$MESOS_EXECUTORINFO_JSON"` an unset variable or do the fields you're looking for just not exist? This environment variable is set directly from whatever the mesos executor sends to the logger module, so it may also depend on the framework you're using (e.g. Marathon, Spark, etc.) for what the contents of that JSON actually are.

**Comment by AbacusIntegrationPlatform** [comment]
I use Marathon framework running on mesos. 
I am using the example file available in Github (https://github.com/wjoel/mesos-external-container-logger/blob/master/examples/filebeat-container-logger.sh)

Should I need to declare or set the variable $MESOS_EXECUTORINFO_JSON or it is Mesos/Marathon system defined variable ? If yes, where and how should I set.

On the side note, and came across the issues on the framework - https://issues.apache.org/jira/browse/MESOS-6003, where it was mentioned to use EXECUTORINFO_JSON. But not sure it is related. 
![image](https://user-images.githubusercontent.com/29430500/34553674-da2da65a-f14e-11e7-8bd5-ae49d4c16f89.png)

**Comment by AbacusIntegrationPlatform** [comment]
Update -
I tried using EXECUTORINFO_JSON variable as well, but that is also coming as null.

**Comment by AbacusIntegrationPlatform** [comment]
Ok found the issue, we need to update the variable name to $MESOS_LOG_EXECUTORINFO_JSON.

The mesos_fields will look like below -

mesos_fields=$(echo "$MESOS_LOG_EXECUTORINFO_JSON" | \
                /u01/mesos/jq-1.5/bin/jq -r ".command.environment.variables
                         |map(\"\(.name):\(.value|tostring)\")|.[]" | \
                # Skip empty variables, use mesos_ prefix, convert to lowercase
                awk -F: 'length($2) > 0 {
                           $1=tolower($1);
                           if (!match($1, "^mesos_.*")) {
                             $1="mesos_" $1;
                           }
                           printf("%s: \"%s\"\n        ", $1, $2);
                         }')

I could able to see all the marathon environment variables in Graylog. Thanks for your help on this.
![image](https://user-images.githubusercontent.com/29430500/34554504-38553d5c-f153-11e7-901f-0e3cee6775da.png)

**Comment by marc-lebourdais** [comment]
Oops, I should have caught the missing environment variable prefix. Glad it's working out for you! I'll close this issue.

**Comment by marc-lebourdais** [comment]
Correction: I don't have the power to do that

**Comment by wjoel** [comment]
Thanks a lot, @marc-lebourdais! I've invited you to be a collaborator on this repository.
