### ISSUE TITLE
mesos-logrotate-logger is not working along with mesos_ExternalContainerLogger

### ISSUE THREAD

**Issue by AbacusIntegrationPlatform** [wjoel/mesos-external-container-logger#4]
I have the config file of filebeat-container-logger.sh as below. It is supposed to output Filebeat as well as in mesos logrotate. But I am able to get the logs only in Filebeat. I have used the configuration provided in the link - https://wjoel.com/posts/mesos-container-log-forwarding-with-filebeat.html. Please let me know if I am doing something wrong.

#!/bin/bash
OUTPUT_HOSTS='["x.x.x.x:5044"]'

config_path="$MESOS_LOG_SANDBOX_DIRECTORY/filebeat-$MESOS_LOG_STREAM.yml"

mesos_fields=$(echo "$MESOS_LOG_EXECUTORINFO_JSON" | \
                /u01/mesos/jq-1.5/bin/jq -r ".command.environment.variables
                         |map(\"\(.name):\(.value|tostring)\")|.[]" | \
                # Skip empty variables, use mesos_ prefix, convert to lowercase
                awk -F: 'length($2) > 0 {
                           $1=tolower($1);
                           if (!match($1, "^mesos_.*")) {
                             $1="mesos_" $1;
                           }
                           printf("%s: \"%s\"\n        ", $1, $2);
                         }')

cat <<EOF > $config_path
filebeat:
  prospectors:
    -
      paths:
        - "-"
      input_type: stdin
      close_eof: true
      fields:
        mesos_log_stream: $MESOS_LOG_STREAM
        mesos_log_sandbox_directory: $MESOS_LOG_SANDBOX_DIRECTORY
        $mesos_fields

output:
  logstash:
    hosts: $OUTPUT_HOSTS
EOF

log_stream=$(echo $MESOS_LOG_STREAM | tr '[:upper:]' '[:lower:]')
tee >(/u01/mesos/libexec/mesos/mesos-logrotate-logger \
        --log_filename="$MESOS_LOG_SANDBOX_DIRECTORY/$log_stream" \
        --logrotate_options="rotate 5" \
        --max_size="10M") | \
/u01/mesos/filebeat-6.1.1-linux-x86_64/filebeat -c $config_path

**Comment by wjoel** [comment]
Does the `mesos-logrotate-logger` command work when you run it separately, just running in a terminal? You may need to specify the full path to to `lograte` with (for example) `--logrotate_path=/usr/sbin/logrotate`.

It's hard to read code you included, since the formatting is destroyed. You can use code blocks in your post as described in https://guides.github.com/features/mastering-markdown/ ("Code" tab under Examples).

**Comment by AbacusIntegrationPlatform** [comment]
liblogrotate_container_logger is working as expected separately. Only when i try to combine filebeat and mesos-logrotate, only Filebeat works. 

I even tried specifying the logrotate_path variable.

my filebeat-container-logger.sh file will look like below -

```
#!/bin/bash
OUTPUT_HOSTS='["x.x.x.x:5044"]'

config_path="$MESOS_LOG_SANDBOX_DIRECTORY/filebeat-$MESOS_LOG_STREAM.yml"

mesos_fields=$(echo "$MESOS_LOG_EXECUTORINFO_JSON" | 
/u01/mesos/jq-1.5/bin/jq -r ".command.environment.variables
|map("(.name):(.value|tostring)")|.[]" | 
# Skip empty variables, use mesos_ prefix, convert to lowercase
awk -F: 'length($2) > 0 {
$1=tolower($1);
if (!match($1, "^mesos_.*")) {
$1="mesos_" $1;
}
printf("%s: "%s"\n ", $1, $2);
}')

cat < $config_path
filebeat:
prospectors:
-
paths:
- "-"
input_type: stdin
close_eof: true
fields:
mesos_log_stream: $MESOS_LOG_STREAM
mesos_log_sandbox_directory: $MESOS_LOG_SANDBOX_DIRECTORY
$mesos_fields

output:
logstash:
hosts: $OUTPUT_HOSTS
EOF

log_stream=$(echo $MESOS_LOG_STREAM | tr '[:upper:]' '[:lower:]')
tee >(/u01/mesos/libexec/mesos/mesos-logrotate-logger 
--log_filename="$MESOS_LOG_SANDBOX_DIRECTORY/$log_stream" 
--logrotate_options="rotate 5"
--logrotate_path=/usr/sbin/logrotate
--max_size="10M") | 
/u01/mesos/filebeat-6.1.1-linux-x86_64/filebeat -c $config_path
```
When i want to use only the mesos logger, below is my mesos-logrotate.json

`{
   "libraries": [
     {
       "file": "/u01/mesos/lib/liblogrotate_container_logger.so",
       "modules": [
         {
           "name": "org_apache_mesos_LogrotateContainerLogger",
           "parameters": [
             {
               "key": "launcher_dir",
               "value": "/u01/mesos/libexec/mesos"
             },
	     {
               "key": "logrotate_path",
               "value": "/u01/mesos/logs"
             }
           ]
         }
       ]
     }
   ]
 }`

How would i combine both. I need filbeat as well as mesos logger module

**Comment by wjoel** [comment]
Does that script work if you run it manually, ie. pipe some file into it, on one of the machines in your cluster? Make sure you try this running as the same user as one of your Mesos applications, and set all the relevant variables to some appropriate values (eg. `export MESOS_LOG_SANDBOX_DIRECTORY=/tmp/test` after you've created that directory). I suspect this is an issue with filebeat, not the logging module itself.

Perhaps more importantly, isn't your mesos-logrotate.json off? It should use `libexternal_container_logger-0.1.0.so` - your logging script should use `mesos-logrotate-logger`, but your Mesos installation should use the external container logger.
