### ISSUE TITLE
Filebeat sessions are not cleared automatically when the stream stops. Even after using -once flag while starting filebeat process

### ISSUE THREAD

**Issue by AbacusIntegrationPlatform** [wjoel/mesos-external-container-logger#5]
Filebeat sessions are not cleared automatically when the stream stops. Even after using -once flag while starting filebeat process.

I have tried to put -once flag along with shutdown_timeout as 0. In this case the logs are not even forwarding to Graylog. Is there a way to clear the filebeat sessions after the container terminates automatically ?

**Comment by wjoel** [comment]
You'd have to solve that in your logging script and/or Filebeat configuration. It's not the responsibility of this logging module. The Filebeat community might be able to help you out. I don't use Filebeat (or Mesos) nowadays.

**Comment by AbacusIntegrationPlatform** [comment]
Thanks WJoel. I will raise an issue with Filebeat for this.

**Comment by wjoel** [comment]
Please add information if you got a solution to this from the Filebeat people. Thanks!
